/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.83
 * Generated at: 2026-04-18 16:43:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Expense Tracker - Login</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: 'Outfit', sans-serif;\n");
      out.write("            background: linear-gradient(135deg, #f4f7fa 0%, #e2e8f0 100%);\n");
      out.write("            height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-card {\n");
      out.write("            background: white;\n");
      out.write("            border-radius: 24px;\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.08);\n");
      out.write("            overflow: hidden;\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 900px;\n");
      out.write("            display: flex;\n");
      out.write("            border: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-left {\n");
      out.write("            background: linear-gradient(135deg, #4318ff 0%, #8f60ff 100%);\n");
      out.write("            color: white;\n");
      out.write("            padding: 50px;\n");
      out.write("            width: 45%;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            justify-content: center;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .login-right {\n");
      out.write("            padding: 60px;\n");
      out.write("            width: 55%;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control {\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 12px 20px;\n");
      out.write("            border: 1px solid #e2e8f0;\n");
      out.write("            background: #f8fafc;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form-control:focus {\n");
      out.write("            box-shadow: none;\n");
      out.write("            border-color: #4318ff;\n");
      out.write("            background: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary {\n");
      out.write("            background: #4318ff;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 12px;\n");
      out.write("            font-weight: 600;\n");
      out.write("            transition: 0.3s;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .btn-primary:hover {\n");
      out.write("            background: #320ddb;\n");
      out.write("            transform: translateY(-2px);\n");
      out.write("            box-shadow: 0 10px 20px rgba(67, 24, 255, 0.2);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .alert-error {\n");
      out.write("            background-color: #fef2f2;\n");
      out.write("            color: #ef4444;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            padding: 12px;\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            font-weight: 500;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            border: 1px solid #fecaca;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"login-card\">\n");
      out.write("        <!-- Left Side Presentation -->\n");
      out.write("        <div class=\"login-left d-none d-md-flex\">\n");
      out.write("            <i class=\"fa-solid fa-wallet mb-4\" style=\"font-size: 4rem;\"></i>\n");
      out.write("            <h2 class=\"fw-bold mb-3\">FinTrack Platform</h2>\n");
      out.write("            <p class=\"opacity-75\" style=\"font-size: 1rem;\">Take control of your personal finances with our intelligent analytical dashboard.</p>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <!-- Right Side Form -->\n");
      out.write("        <div class=\"login-right\">\n");
      out.write("            <div class=\"mb-5 text-center\">\n");
      out.write("                <h3 class=\"fw-bold\" style=\"color: #1e293b;\">Welcome Back</h3>\n");
      out.write("                <p class=\"text-muted\">Please sign in to access your dashboard.</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("                <div class=\"alert-error\">\n");
      out.write("                    <i class=\"fa-solid fa-circle-exclamation me-2\"></i> ");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            ");
 if ("success".equals(request.getParameter("logout"))) { 
      out.write("\n");
      out.write("                <div class=\"alert-error\" style=\"background: #ecfdf5; color: #10b981; border-color: #a7f3d0;\">\n");
      out.write("                    <i class=\"fa-solid fa-check-circle me-2\"></i> Successfully logged out.\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/login\" method=\"POST\">\n");
      out.write("                <div class=\"mb-4\">\n");
      out.write("                    <label class=\"form-label text-muted fw-bold small\">Email Address</label>\n");
      out.write("                    <input type=\"text\" name=\"email\" class=\"form-control\" placeholder=\"sharayu@tracker.com\" value=\"sharayu@tracker.com\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"mb-4\">\n");
      out.write("                    <label class=\"form-label text-muted fw-bold small d-flex justify-content-between\">\n");
      out.write("                        Password\n");
      out.write("                    </label>\n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"••••••••\" value=\"password123\" required>\n");
      out.write("                    <div class=\"form-text mt-2\"><small>Demo password is <strong>password123</strong></small></div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary w-100 mt-2\">Sign In to Dashboard</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
